# Generated by Django 4.0.4 on 2022-05-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('rating', models.FloatField()),
                ('img_url', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
