# the questions are taken from https://opentdb.com
question_data = [{"category": "Animals", "type": "boolean", "difficulty": "easy",
                  "question": "Kangaroos keep food in their pouches next to their children.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "The United States was a member of the League of Nations.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Film", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In the original script of &quot;The Matrix&quot;, the machines used humans as additional computing power instead of batteries.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Gadgets", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Microphones can be used not only to pick up sound, but also to project sound similar to a speaker.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science & Nature", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Psychology is the science of behavior and mind.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "Nova Scotia is on the east coast of Canada.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Mythology", "type": "boolean", "difficulty": "easy",
                  "question": "A wyvern is the same as a dragon.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Slovakia is a member of European Union-",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "In the video game &quot;Splatoon&quot;, the playable characters were originally going to be rabbits instead of squids.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Each piece in Tetris is called a tetris.",
                  "correct_answer": "False", "incorrect_answers": ["True"]}]
